- id: '1594046745791'
  alias: Restart F2_0_Hub everyday
  description: Restart Floor 2 - Office - Hub everyday
  trigger:
  - at: 00:00:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.f2_o_hub_restart
    service: switch.turn_on
- id: '1594066196204'
  alias: Bedrooms Night Mode
  description: Turn on mosquito switches on bedrooms at 21:00
  trigger:
  - at: '21:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.f1_mb_mosquito_switch
    service: switch.turn_on
  - data: {}
    entity_id: switch.f1_kb_mosquito_switch
    service: switch.turn_on
- id: '1594066278278'
  alias: Bedrooms Day Mode
  description: Turn off mosquito switches on bedrooms at 6:00
  trigger:
  - at: 06:00:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.f1_kb_mosquito_switch
    service: switch.turn_off
  - data: {}
    entity_id: switch.f1_mb_mosquito_switch
    service: switch.turn_off
- id: '1594106565686'
  alias: Change theme day/night
  description: Change theme on sunset and sunrise
  trigger:
  - event: start
    platform: homeassistant
  - entity_id: sun.sun
    platform: state
    to: above_horizon
  - entity_id: sun.sun
    platform: state
    to: below_horizon
  condition: []
  action:
  - data_template:
      name: '{{ "clear" if is_state("sun.sun", "above_horizon") else "clear-dark"
        }}'
    service: frontend.set_theme