homeassistant:
  name: "Home"
  latitude: !secret zones_home_latitude
  longitude: !secret zones_home_longitude
  elevation: !secret zones_home_elevation
  unit_system: metric
  time_zone: "Europe/Madrid"
  packages: !include_dir_named packages

config:
ffmpeg:
history:

http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

logbook:
map:
mobile_app:
sun:
system_health:
wake_on_lan:
zone: !include zones.yaml