homeassistant:
  name: "Home"
  latitude: !secret zones_home_latitude
  longitude: !secret zones_home_longitude
  elevation: !secret zones_home_elevation
  unit_system: metric
  time_zone: "Europe/Madrid"
  packages: !include_dir_named packages
  external_url: !secret homeassistant_external_url
  internal_url: !secret homeassistant_internal_url
  customize: !include customize.yaml

automation: !include automations.yaml

alexa:
  smart_home:
api:
config:
ffmpeg:
history:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

logbook:
map:
mobile_app:
sun:
system_health:
wake_on_lan:
zone: !include zones.yaml

sensor:
  - platform: time_date
    display_options:
      - 'time_utc'
      - 'time'