title: Home

views:
  - id: 0
    icon: mdi:home
    name: Home
    path: home
    badges: [
      "person.dani",
      "sun.sun"
    ]
    cards:
      - type: weather-forecast
        entity: weather.home
  - id: 1
    icon: mdi:home-floor-0
    name: Floor 0
    path: floor_0
    cards:
      - type: entities
        title: Living Room
        show_header_toggle: false
        entities:
          - type: section
            label: Orchid
          - entity: sensor.living_room_mi_flora_01_moisture
            name: Moisture
          - entity: sensor.living_room_mi_flora_01_temperature
            name: Temperature
          - entity: sensor.living_room_mi_flora_01_light_intensity
            name: Light Intensity
          - entity: sensor.living_room_mi_flora_01_conductivity
            name: Conductivity
          - entity: sensor.living_room_mi_flora_01_battery
            name: Battery
          - type: plant-status
            entity: plant.living_room_orchid
            name: Orchid
          - type: divider
          - entity: media_player.webos_tv_lf652v
            name: Television
      - type: vertical-stack
        cards:
          - type: plant-status
            entity: plant.living_room_orchid
          - type: media-control
            entity: media_player.webos_tv_lf652v
      - type: entities
        title: Utility
        show_header_toggle: false
        entities:
          - entity: switch.81353660600194c9dbfe
            name: Washing Machine
      - type: entities
        title: Landing
        show_header_toggle: false
        entities:
          - entity: camera.camera_sp009
            name: Camera
      - type: entities
        title: Garage
        show_header_toggle: false
        entities:
          - entity: camera.rpi0w_meye_20f5d0f5
            name: Camera
  - id: 2
    icon: mdi:home-floor-1
    name: Floor 1
    path: floor_1
    cards:
      - type: entities
        title: Master Bedroom
        show_header_toggle: false
        entities:
          - entity: media_player.webos_tv_lm6300pla
            name: Television
      - type: media-control
        entity: media_player.webos_tv_lm6300pla
  - id: 3
    icon: mdi:home-floor-2
    name: Floor 2
    path: floor_2
    cards:
      - type: entities
        title: Office
        show_header_toggle: false
        entities:
          - entity: sensor.esp8266_01_temperature
            name: Temperature
          - entity: sensor.esp8266_01_humidity
            name: Humidity
  - id: 4
    icon: mdi:engine
    name: System
    path: system
    cards:
      - cards:
          - cards:
              - type: gauge
                entity: sensor.processor_use
              - type: gauge
                entity: sensor.disk_use_percent
              - type: gauge
                entity: sensor.memory_use_percent
            type: horizontal-stack
          - entities:
              - sensor.last_boot
            type: entities
        type: vertical-stack
      - entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
        type: history-graph
      - type: entities
        title: Automations
        entities:
          - automation.notification_telegram_mi_flora_01_moisture
      - type: entities
        title: Second Floor
        show_header_toggle: false
        entities:
          - type: section
            label: Office Probe
          - entity: binary_sensor.esp8266_01_status
            name: Status
          - entity: sensor.esp8266_01_wifi_signal_sensor
            name: WiFi Signal
          - entity: sensor.esp8266_01_esphome_version
            name: ESPHome Version