title: Home

views:
  - id: 0
    icon: mdi:home
    name: Home
    path: home
    badges: [
      "person.dani",
      "sun.sun"
    ]
    cards:
      - type: weather-forecast
        entity: weather.home
      - type: plant-status
        entity: plant.living_room_orchid
      - type: entities
        title: Switches
        entities:
          - switch.81353660600194c9dbfe
  - id: 1
    icon: mdi:engine
    name: System
    path: system
    cards:
      - cards:
          - cards:
              - type: gauge
                entity: sensor.processor_use
              - type: gauge
                entity: sensor.disk_use_percent
              - type: gauge
                entity: sensor.memory_use_percent
            type: horizontal-stack
          - entities:
              - sensor.last_boot
            type: entities
        type: vertical-stack
      - entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
        type: history-graph
      - type: entities
        title: Automations
        entities:
          - automation.notification_telegram_mi_flora_01_moisture