title: Home
views:
  - id: 0
    icon: mdi:home
    name: Home
    path: home
    badges:
      - person.dani
      - sensor.home_mean_temperature
      - switch.boiler_heating
    cards:
      - type: thermostat
        entity: climate.home_thermostat
      - type: weather-forecast
        entity: weather.home
  - id: 1
    icon: mdi:home-floor-0
    name: Ground Floor
    path: ground_floor
    badges:
      - person.dani
      - sensor.ground_floor_mean_temperature
      - switch.boiler_heating
    cards:
      - type: thermostat
        entity: climate.ground_floor_thermostat
      - type: glance
        title: Living Room
        show_name: false
        entities:
          - entity: sensor.esp32_01_temperature
            name: Temperature
          - entity: sensor.esp32_01_humidity
            name: Humidity
          - plant.orchid
          - entity: media_player.webos_tv_lf652v
            name: Television
      - type: glance
        title: Garage
        entities:
          - entity: switch.blitzwolf_shp2_01_switch
            name: Blanket
          - entity: camera.camera_sp009
            name: Camera
          - entity: sensor.esp32_02_temperature
            name: Temperature
          - entity: sensor.esp32_02_humidity
            name: Humidity      
      - type: glance
        title: Landing
        show_name: false
        entities:
          - entity: camera.rpi0w_meye_20f5d0f5
            name: Camera
  - id: 2
    icon: mdi:home-floor-1
    name: First Floor
    path: first_floor
    badges:
      - person.dani
      - sensor.first_floor_mean_temperature
      - switch.boiler_heating
    cards:
      - type: thermostat
        entity: climate.first_floor_thermostat
      - type: glance
        title: Kid's Room
        show_name: false
        entities:
          - entity: sensor.esp32_03_temperature
            name: Temperature
          - entity: sensor.esp32_03_humidity
            name: Humidity
      - type: glance
        title: Master Bedroom
        show_name: false
        entities:
          - entity: sensor.esp8266_02_temperature
            name: Temperature
          - entity: sensor.esp8266_02_humidity
            name: Humidity
          - entity: media_player.webos_tv_lm6300pla
            name: Television
      - type: glance
        title: Play Room
        show_name: false
        entities:
          - entity: sensor.esp32_cam_01_temperature
            name: Temperature
          - entity: sensor.esp32_cam_01_humidity
            name: Humidity
          - entity: camera.esp32_cam_01_camera
            name: Camera
          - entity: light.esp32_cam_01_light
            name: Camera Light
  - id: 3
    icon: mdi:home-floor-2
    name: Second Floor
    path: second_floor
    badges:
      - person.dani
      - switch.boiler_heating
    cards:
  - id: 4
    icon: mdi:engine
    name: System
    path: system
    badges:
      - person.dani
      - switch.boiler_heating
    cards:
      - cards:
          - cards:
              - type: gauge
                entity: sensor.processor_use
              - type: gauge
                entity: sensor.disk_use_percent
              - type: gauge
                entity: sensor.memory_use_percent
            type: horizontal-stack
          - entities:
              - sensor.last_boot
            type: entities
        type: vertical-stack
      - entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
        type: history-graph
      - type: entities
        title: Automations
        entities:          
          - automation.change_theme
          - automation.telegram_send_message_on_mijia_flora_01_moisture_is_low
          - automation.turn_on_off_garage_blanket
      - type: glance
        title: Status
        columns: 3
        show_state: false
        entities:
          - entity: binary_sensor.esp32_01_status
            name: ESP32-01
          - entity: binary_sensor.esp32_02_status
            name: ESP32-02
          - entity: binary_sensor.esp32_03_status
            name: ESP32-03
          - entity: binary_sensor.esp32_cam_01_status
            name: ESP32-CAM-01
          - entity: binary_sensor.esp8266_01_status
            name: ESP8266-01
          - entity: binary_sensor.esp8266_02_status
            name: ESP8266-02
          - entity: binary_sensor.boiler_status
            name: Boiler
          - entity: binary_sensor.blitzwolf_shp2_01_status
            name: Blitzwolf SHP2 (01)
      - type: glance
        title: Batteries
        show_header_toggle: false
        entities:
          - sensor.xiaomi_mijia_flora_01_battery_level
