title: Home

views:
  - id: 0
    icon: mdi:home
    name: Home
    path: home
    badges: [
      "person.dani",
      "sun.sun"
    ]
    cards:
      - type: weather-forecast
        entity: weather.home
      - type: entities
        entities:
          - switch.boiler_heating
  - id: 1
    icon: mdi:home-floor-0
    name: Floor 0
    path: floor_0
    cards:
      - type: glance
        title: Living Room
        show_name: false
        entities:
          - entity: sensor.esp32_01_temperature
            name: Temperature
          - entity: sensor.esp32_01_humidity
            name: Humidity
          - plant.living_room_orchid
          - entity: media_player.webos_tv_lf652v
            name: Television
      - type: entities
        title: Utility
        show_header_toggle: false
        entities:
          - entity: switch.81353660600194c9dbfe
            name: Washing Machine
      - type: entities
        title: Garage
        show_header_toggle: false
        entities:
          - entity: sensor.esp8266_01_temperature
            name: Temperature
          - entity: sensor.esp8266_01_humidity
            name: Humidity
          - entity: camera.camera_sp009
            name: Camera
      - type: entities
        title: Landing
        show_header_toggle: false
        entities:
          - entity: camera.rpi0w_meye_20f5d0f5
            name: Camera
  - id: 2
    icon: mdi:home-floor-1
    name: Floor 1
    path: floor_1
    cards:
      - type: glance
        title: Hallway
        show_name: false
        entities:
          - entity: sensor.esp32_03_temperature
            name: Temperature
          - entity: sensor.esp32_03_humidity
            name: Humidity
      - type: glance
        title: Kid's Bedroom
        show_name: false
        entities:
          - entity: sensor.esp32_02_temperature
            name: Temperature
          - entity: sensor.esp32_02_humidity
            name: Humidity
          - entity: camera.esp32_cam_01_camera
            name: Camera
          - entity: light.esp32_cam_01_light
            name: Camera Light
      - type: glance
        title: Master Bedroom
        show_name: false
        entities:
          - entity: sensor.esp8266_02_temperature
            name: Temperature
          - entity: sensor.esp8266_02_humidity
            name: Humidity
          - entity: media_player.webos_tv_lm6300pla
            name: Television
  - id: 3
    icon: mdi:home-floor-2
    name: Floor 2
    path: floor_2
    cards:
  - id: 4
    icon: mdi:engine
    name: System
    path: system
    cards:
      - cards:
          - cards:
              - type: gauge
                entity: sensor.processor_use
              - type: gauge
                entity: sensor.disk_use_percent
              - type: gauge
                entity: sensor.memory_use_percent
            type: horizontal-stack
          - entities:
              - sensor.last_boot
            type: entities
        type: vertical-stack
      - entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
        type: history-graph
      - type: entities
        title: Automations
        entities:
          - automation.telegram_send_message_on_mijia_flora_01_moisture_is_low
      - type: glance
        title: Status
        columns: 3
        show_state: false
        entities:
          - entity: binary_sensor.esp32_01_status
            name: ESP32-01
          - entity: binary_sensor.esp32_02_status
            name: ESP32-02
          - entity: binary_sensor.esp32_03_status
            name: ESP32-03
          - entity: binary_sensor.esp32_cam_01_status
            name: ESP32-CAM-01
          - entity: binary_sensor.esp8266_01_status
            name: ESP8266-01
          - entity: binary_sensor.esp8266_02_status
            name: ESP8266-02
          - entity: binary_sensor.boiler_status
            name: Boiler
      - type: glance
        title: Batteries
        show_header_toggle: false
        entities:
          - sensor.xiaomi_mijia_flora_01_battery_level
