---
platform: bme280
update_interval: ${default_update_interval}
temperature:
    name: ${upper_devicename} Temperature
    id: ${devicename}_temperature
pressure:
    name: ${upper_devicename} Pressure
    id: ${devicename}_pressure
humidity:
    name: ${upper_devicename} Humidity
    id: ${devicename}_humidity
address: 0x76