substitutions:
  devicename: esp32_01
  upper_devicename: ESP32-01
  xiaomi_HHCCJCY01_devicename: xiaomi_hhccjcy01_01
  xiaomi_HHCCJCY01_upper_devicename: Xiaomi Mijia Flora 01
  default_update_interval: 60s

esphome:
  name: ${devicename}
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret base_wifi_ssid
  password: !secret base_wifi_password
  manual_ip:
    static_ip: !secret esp32_01_wifi_manual_ip_static_ip
    gateway: !secret esp32_01_wifi_manual_ip_gateway
    subnet: !secret esp32_01_wifi_manual_ip_subnet

api:
  password: !secret esp32_01_api_password

ota:
  password: !secret esp32_01_ota_password

logger:

i2c:
  - sda: GPIO21
    scl: GPIO22

esp32_ble_tracker:

sensor:
  - platform: bme280
    update_interval: ${default_update_interval}
    temperature:
      name: ${upper_devicename} Temperature
      id: ${devicename}_temperature
    pressure:
      name: ${upper_devicename} Pressure
      id: ${devicename}_pressure
    humidity:
      name: ${upper_devicename} Humidity
      id: ${devicename}_humidity
    address: 0x76
  - platform: xiaomi_hhccjcy01
    mac_address: !secret xiaomi_hhccjcy01_01_mac
    temperature:
      name: ${xiaomi_HHCCJCY01_upper_devicename} Temperature
      id: ${xiaomi_HHCCJCY01_devicename}_temperature
    moisture:
      name: ${xiaomi_HHCCJCY01_upper_devicename} Moisture
      id: ${xiaomi_HHCCJCY01_devicename}_moisture
    illuminance:
      name: ${xiaomi_HHCCJCY01_upper_devicename} Brightness
      id: ${xiaomi_HHCCJCY01_devicename}_brightness
    conductivity:
      name: ${xiaomi_HHCCJCY01_upper_devicename} Soil Conductivity
      id: ${xiaomi_HHCCJCY01_devicename}_conductivity
    battery_level:
      name: ${xiaomi_HHCCJCY01_upper_devicename} Battery Level
      id: ${xiaomi_HHCCJCY01_devicename}_battery

binary_sensor:
  - platform: status
    name: ${upper_devicename} Status
    id: ${devicename}_status

status_led:
  pin: GPIO2
