substitutions:
  devicename: esp32_01
  upper_devicename: ESP32-01
  xiaomi_HHCCJCY01_devicename: xiaomi_hhccjcy01_01
  xiaomi_HHCCJCY01_upper_devicename: Xiaomi Mijia Flora 01
  default_update_interval: 60s

esphome:
  name: ${devicename}
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret base_wifi_ssid
  password: !secret base_wifi_password
  power_save_mode: none
  manual_ip:
    static_ip: !secret esp32_01_wifi_manual_ip_static_ip
    gateway: !secret base_wifi_manual_ip_gateway
    subnet: !secret base_wifi_manual_ip_subnet

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

i2c:
  - sda: GPIO21
    scl: GPIO22

esp32_ble_tracker:

sensor:
  - !include common/sensor/bme280.yaml
  - platform: xiaomi_hhccjcy01
    mac_address: !secret xiaomi_hhccjcy01_01_mac
    temperature:
      name: ${xiaomi_HHCCJCY01_upper_devicename} Temperature
      id: ${xiaomi_HHCCJCY01_devicename}_temperature
    moisture:
      name: ${xiaomi_HHCCJCY01_upper_devicename} Moisture
      id: ${xiaomi_HHCCJCY01_devicename}_moisture
    illuminance:
      name: ${xiaomi_HHCCJCY01_upper_devicename} Brightness
      id: ${xiaomi_HHCCJCY01_devicename}_brightness
    conductivity:
      name: ${xiaomi_HHCCJCY01_upper_devicename} Soil Conductivity
      id: ${xiaomi_HHCCJCY01_devicename}_conductivity
    battery_level:
      name: ${xiaomi_HHCCJCY01_upper_devicename} Battery Level
      id: ${xiaomi_HHCCJCY01_devicename}_battery

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin: GPIO2