substitutions:
  devicename: esp32_cam_01
  upper_devicename: ESP32-CAM-01
  default_update_interval: 60s

esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32cam

wifi:
  ssid: !secret base_wifi_ssid
  password: !secret base_wifi_password
  manual_ip:
    static_ip: !secret esp32_cam_01_wifi_manual_ip_static_ip
    gateway: !secret base_wifi_manual_ip_gateway
    subnet: !secret base_wifi_manual_ip_subnet

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

i2c:
  - sda: GPIO13
    scl: GPIO14

sensor:
  - !include common/sensor/bme280.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin: 
    number: GPIO33
    inverted: true

output:
  - platform: gpio
    pin: GPIO4
    id: led

light:
  - platform: binary
    name: ${upper_devicename} Light
    id: ${devicename}_light
    output: led

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: ${upper_devicename} Camera
  id: ${devicename}_camera
