substitutions:
  devicename: esp32_03
  upper_devicename: ESP32-03
  default_update_interval: 60s

esphome:
  name: ${devicename}
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret base_wifi_ssid
  password: !secret base_wifi_password
  manual_ip:
    static_ip: !secret esp32_03_wifi_manual_ip_static_ip
    gateway: !secret base_wifi_manual_ip_gateway
    subnet: !secret base_wifi_manual_ip_subnet

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml

i2c:
  - sda: GPIO21
    scl: GPIO22

sensor:
  - !include common/sensor/bme280.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin: GPIO2
