substitutions:
  devicename: esp8266_01
  upper_devicename: ESP8266_01
  default_update_interval: 60s

esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret base_wifi_ssid
  password: !secret base_wifi_password
  manual_ip:
    static_ip: 192.168.1.21
    gateway: 192.168.1.1
    subnet: 255.255.255.0

sensor:
  - platform: dht
    pin: D2
    model: AM2302
    temperature:
      name: ${upper_devicename} Temperature
    humidity:
      name: ${upper_devicename} Humidity
    update_interval: ${default_update_interval}
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
    id: ${devicename}_wifi_signal
    update_interval: ${default_update_interval}

binary_sensor:
  - platform: status
    name: ${upper_devicename} Status
    
text_sensor:
  - platform: version
    name: ${upper_devicename} ESPHome Version
    id: ${devicename}_esphome_version

status_led:
  pin:
    number: D1

logger:

api:
  password: !secret esp8266_01_api_password

ota:
  password: !secret esp8266_01_ota_password