base_wifi_ssid: XXXXXXXXXX
base_wifi_password: XXXXXXXXXX

esp8266_01_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
esp8266_01_wifi_manual_ip_gateway: XXX.XXX.XXX.XXX
esp8266_01_wifi_manual_ip_subnet: XXX.XXX.XXX.XXX

esp8266_01_api_password: XXXXXXXXXX
esp8266_01_ota_password: XXXXXXXXXX