base_wifi_ssid: XXXXXXXXXX
base_wifi_password: XXXXXXXXXX

esp32_01_api_password: XXXXXXXXXX
esp32_01_ota_password: XXXXXXXXXX

esp32_01_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
esp32_01_wifi_manual_ip_gateway: XXX.XXX.XXX.XXX
esp32_01_wifi_manual_ip_subnet: XXX.XXX.XXX.XXX

esp32_02_api_password: XXXXXXXXXX
esp32_02_ota_password: XXXXXXXXXX

esp32_02_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
esp32_02_wifi_manual_ip_gateway: XXX.XXX.XXX.XXX
esp32_02_wifi_manual_ip_subnet: XXX.XXX.XXX.XXX

esp32_03_api_password: XXXXXXXXXX
esp32_03_ota_password: XXXXXXXXXX

esp32_03_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
esp32_03_wifi_manual_ip_gateway: XXX.XXX.XXX.XXX
esp32_03_wifi_manual_ip_subnet: XXX.XXX.XXX.XXX

esp8266_01_api_password: XXXXXXXXXX
esp8266_01_ota_password: XXXXXXXXXX

esp8266_01_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
esp8266_01_wifi_manual_ip_gateway: XXX.XXX.XXX.XXX
esp8266_01_wifi_manual_ip_subnet: XXX.XXX.XXX.XXX

esp8266_02_api_password: XXXXXXXXXX
esp8266_02_ota_password: XXXXXXXXXX

esp8266_02_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
esp8266_02_wifi_manual_ip_gateway: XXX.XXX.XXX.XXX
esp8266_02_wifi_manual_ip_subnet: XXX.XXX.XXX.XXX
