base_wifi_ssid: XXXXXXXXXX
base_wifi_password: XXXXXXXXXX
base_wifi_manual_ip_gateway: XXX.XXX.XXX.XXX
base_wifi_manual_ip_subnet: XXX.XXX.XXX.XXX
base_api_password: XXXXXXXXXX
base_ota_password: XXXXXXXXXX

blitzwolf_shp2_01_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
boiler_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
esp32_01_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
esp32_02_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
esp32_03_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
esp32_cam_01_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
esp8266_01_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX
esp8266_02_wifi_manual_ip_static_ip: XXX.XXX.XXX.XXX

xiaomi_hhccjcy01_01_mac: XXX.XXX.XXX.XXX