homeassistant:
  customize:
    switch.m_plug_switch:
      friendly_name: "Acuario - Luz"
    binary_sensor.m_plug_status:
      friendly_name: "Acuario - Conectividad"

input_datetime:
  f0_lr_aquarium_light_time_start:
    name: Hour to Turn On Aquarium Light
    has_date: false
    has_time: true
    icon: mdi:clock-start
  f0_lr_aquarium_light_time_end:
    name: Hour to Turn Off Aquarium Light
    has_date: false
    has_time: true
    icon: mdi:clock-end

automation:
  - id: '1594066196111'
    alias: "Acuario - Encender Luz Autom치ticamente"
    description: "Encender la luz del Acuario del Sal칩n a la hora configurada"
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.f0_lr_aquarium_light_time_start', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - entity_id: switch.m_plug_switch
        service: switch.turn_on
  - id: '1594066196112'
    alias: "Acuario - Apagar Luz Autom치ticamente"
    description: "Apagar la luz del Acuario del Sal칩n a la hora configurada"
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.f0_lr_aquarium_light_time_end', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - entity_id: switch.m_plug_switch
        service: switch.turn_off