homeassistant:
  customize:
    camera.f0_g_camera:
      friendly_name: "Garaje - Camara"
    camera.f0_e_camera:
      friendly_name: "Entrada - Camara"
  customize_glob:
    camera.*:
      icon: mdi:cctv
      
camera:
  # Sricam SP009
  - platform: ffmpeg
    name: "f0_g_camera"
    input: !secret f0_g_camera_input
    extra_arguments: -an
  # Raspberry Pi Zero + Motion Eye
  - platform: mjpeg
    name: "f0_e_camera"
    mjpeg_url: !secret f0_e_camera_url
    username: !secret f0_e_camera_user
    password: !secret f0_e_camera_password
    authentication: basic
