homeassistant:
  customize:
    camera.garage_camera:
      friendly_name: "Garaje - Cámara"
    camera.entrance_camera:
      friendly_name: "Entrada - Cámara"
  customize_glob:
    camera.*:
      icon: mdi:cctv

stream:

camera:
  # Sricam SP009
  - platform: ffmpeg
    name: garage_camera
    input: !secret garage_camera_input
    extra_arguments: -an
  # Raspberry Pi Zero + Motion Eye
  - platform: mjpeg
    name: entrance_camera
    mjpeg_url: !secret entrance_camera_url
    username: !secret entrance_camera_user
    password: !secret entrance_camera_password
    authentication: basic
