homeassistant:
  customize_glob:
    sensor.*_meantemperature:
      device_class: temperature
      icon: mdi:thermometer
  customize:
    automation.home_thermostat_turnupthetemperatureatmorning:
      friendly_name: Casa - Termostato - Subir a 22ยบ a las 6:00
      icon: mdi:thermometer-chevron-up
    climate.home_thermostat:
      friendly_name: Casa - Termostato
    climate.groundfloor_thermostat:
      friendly_name: Planta Baja - Termostato
    climate.firstfloor_thermostat:
      friendly_name: Primera Planta - Termostato
    climate.secondfloor_thermostat:
      friendly_name: Segunda Planta - Termostato
    sensor.home_meantemperature:
      friendly_name: Casa - Temperatura Media
    sensor.groundfloor_meantemperature:
      friendly_name: Planta Baja - Temperatura Media
    sensor.firstfloor_meantemperature:
      friendly_name: Primera Planta - Temperatura Media
    sensor.secondfloor_meantemperature:
      friendly_name: Segunda Planta - Temperatura Media

automation:
  - id: home_thermostat_turnupthetemperatureatmorning
    alias: "Home - Thermostat - TurnUpTheTemperatureAtMorning"
    description: "Set target temperature at home to 22ยบ at 06:00:00 if automatic thermostat is enabled"
    trigger:
      - platform: time
        at: 06:00:00
    condition:
      - condition: state
        entity_id: climate.home_thermostat
        state: heat
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.home_thermostat
          hvac_mode: heat
          temperature: 22

climate:
  - platform: generic_thermostat
    name: home_thermostat
    heater: switch.home_heater_switch
    target_sensor: sensor.home_meantemperature
    initial_hvac_mode: "off"
    away_temp: 19
    target_temp: 22
  - platform: generic_thermostat
    name: groundfloor_thermostat
    heater: switch.home_heater_switch
    target_sensor: sensor.groundfloor_meantemperature
    initial_hvac_mode: "off"
    away_temp: 19
    target_temp: 22
  - platform: generic_thermostat
    name: firstfloor_thermostat
    heater: switch.home_heater_switch
    target_sensor: sensor.firstfloor_meantemperature
    initial_hvac_mode: "off"
    away_temp: 19
    target_temp: 22
  - platform: generic_thermostat
    name: secondfloor_thermostat
    heater: switch.home_heater_switch
    target_sensor: sensor.secondfloor_meantemperature
    initial_hvac_mode: "off"
    away_temp: 19
    target_temp: 22

sensor:
  - platform: min_max
    name: home_meantemperature
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.groundfloor_meantemperature
      - sensor.firstfloor_meantemperature
      - sensor.secondfloor_meantemperature
  - platform: min_max
    name: groundfloor_meantemperature
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.kitchen_hub_temperature
      - sensor.livingroom_hub_temperature
  - platform: min_max
    name: firstfloor_meantemperature
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.kidsbedroom_hub_temperature
      - sensor.masterbedroom_hub_temperature
  - platform: min_max
    name: secondfloor_meantemperature
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.office_hub_temperature
