sensor:
  - platform: template
    sensors:
      electricperiod:
        friendly_name: "Periodo Eléctrico"
        unique_id: electricperiod
        value_template: "{{ 'valle' if states('sensor.time_utc') >= '21:00' or states('sensor.time_utc') < '11:00' else 'pico' }}"
        icon_template: "{{ 'mdi:brightness-2' if states('sensor.time_utc') >= '21:00' or states('sensor.time_utc') < '11:00' else 'mdi:brightness-5' }}"
