automation:
  - id: change_theme
    alias: "Change theme"
    description: "Change between light and dark theme when sunset or sunrise or the server starts"
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sun.sun
        to: "above_horizon"
      - platform: state
        entity_id: sun.sun
        to: "below_horizon"
    action:
      - service: frontend.set_theme
        data_template:
          name: "{{ 'clear' if is_state('sun.sun', 'above_horizon') else 'clear-dark' }}"

frontend:
  themes: !include_dir_merge_named ../themes/

lovelace:
  mode: yaml
  resources:
    - url: /local/pvpc-hourly-pricing-card/dist/pvpc-hourly-pricing-card.js?v=0.0.3
      type: module
  dashboards:
    lovelace-generated:
      mode: yaml
      filename: notexist.yaml
      title: "Generated"
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true