binary_sensor:
  - platform: tod
    name: TimeOfDay Day
    after: sunrise
    before: sunset
  - platform: tod
    name: TimeOfDay Night
    after: sunset
    before: sunrise

automation:
  - id: '1594066196101'
    alias: Floor 1 - Kids' Bedroom - Night Mode
    description: Turn on Kids' Bedroon Night Mode scene on binary_sensor.timeofday_night
    trigger:
      platform: state
      entity_id: binary_sensor.timeofday_night
      to: "on"
    action:
      service: scene.turn_on
      entity_id: scene.floor_1_kids_bedroom_night_mode
  - id: '1594066196102'
    alias: Floor 1 - Kids' Bedroom - Day Mode
    description: Turn on Kids' Bedroon Day Mode scene on binary_sensor.timeofday_day
    trigger:
      platform: state
      entity_id: binary_sensor.timeofday_day
      to: "on"
    action:
      service: scene.turn_on
      entity_id: scene.floor_1_kids_bedroom_day_mode

scene:
  - name: Floor 1 - Kids' Bedroom - Night Mode
    icon: "mdi:brightness-4"
    entities:
      switch.f1_kb_mosquito_switch: "on"
  - name: Floor 1 - Kids' Bedroom - Day Mode
    icon: "mdi:brightness-5"
    entities:
      switch.f1_kb_mosquito_switch: "off"