input_datetime:
  f1_mb_nightmode_time_start:
    name: Hour to Start Night Mode
    has_date: false
    has_time: true
    icon: mdi:clock-start
  f1_mb_daymode_time_start:
    name: Hour to Start Day Mode
    has_date: false
    has_time: true
    icon: mdi:clock-end

automation:
  - id: '1594066196206'
    alias: Floor 1 - Master Bedroom - Night Mode
    description: Turn on Master Bedroon Night Mode scene on f1_mb_nightmode_time_start
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.f1_mb_nightmode_time_start', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
      service: scene.turn_on
      entity_id: scene.floor_1_master_bedroom_night_mode
  - id: '1594066196289'
    alias: Floor 1 - Master Bedroom - Day Mode
    description: Turn on Master Bedroon Day Mode scene on f1_mb_daymode_time_start
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.f1_mb_daymode_time_start', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
      service: scene.turn_on
      entity_id: scene.floor_1_master_bedroom_day_mode

scene:
  - name: Floor 1 - Master Bedroom - Night Mode
    icon: "mdi:brightness-4"
    entities:
      switch.f1_mb_mosquito_switch: "on"
  - name: Floor 1 - Master Bedroom - Day Mode
    icon: "mdi:brightness-5"
    entities:
      switch.f1_mb_mosquito_switch: "off"